name:                file-rename
version:             0.1.0.0
github:              "JakuJ/file-rename"
license:             BSD3
author:              "Jakub Janaszkiewicz"
maintainer:          "janaszkiewicz.jakub@gmail.com"
copyright:           "Jakub Janaszkiewicz"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/JakuJ/file-rename#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- unix
- parsec
- time

library:
  source-dirs: src

executables:
  file-rename-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - file-rename